site_name: view.py
site_url: https://view.zintensity.dev
repo_url: https://github.com/ZeroIntensity/view.py
repo_name: ZeroIntensity/view.py

nav:
    - Home: index.md
    - User Guide:
      - user-guide/index.md
      - Creating an app: user-guide/creating.md
      - Running: user-guide/running.md
      - Responses: user-guide/responses.md
      - Parameters: user-guide/parameters.md
      - Documenting Your App: user-guide/docs.md
      - Reference: user-guide/reference.md
    - Development Guide:
      - dev-guide/index.md
      - Workflow: dev-guide/workflow.md
      - App: dev-guide/app.md
      - Routing: dev-guide/routing.md
      - Loader: dev-guide/loader.md
      - Logging: dev-guide/logging.md

theme:
    name: null
    custom_dir: "html/"

markdown_extensions:
  - admonition

plugins:
    - mkdocstrings:
          handlers:
              python:
                  paths: [src]
