name: Feature request
description: Suggest an idea for this project.
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Please, fill this form to help us improve the project.
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A clear and concise description of what you want to happen.
      placeholder: |
        For example, a request for adding foo to view.bar could look like:
        **Description:** This adds support for foo to bar
    validations:
      required: true
  - type: textarea
    id: example-API
    attributes:
      label: Feature example API
      description: Provide an example of what you want to happen.
      placeholder: |
        For example, a request for adding foo to view.bar could look like:
        **Example API:**
        view.bar.foo(...)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Add any other context or screenshots about the feature request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
