name: Improvement request
description: Suggest an improvement for this project.
title: "[Improvement Request]: "
labels: ["improvement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this improvement request! Please, fill this form to help us improve the project.
  - type: textarea
    id: description
    attributes:
      label: Improvement Description
      description: A clear and concise description of what you want to happen.
      placeholder: |
        For example, a request for improving foo in view.bar could look like:
        **Description:** This improves foo in bar
    validations:
      required: true
  - type: textarea
    id: example-API
    attributes:
      label: Improvement Request Example API
      description: Provide an example of what you want to happen.
      placeholder: |
        For example, an improvement request for improving foo in view.bar could look like:
        **Example API:**
        view.bar.foo(...)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Add any other context or screenshots about the improvement request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
