name: Question
description: Ask a question
title: "[Question]: "
labels: ["question"] 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask this question!
  - type: checkboxes
    attributes:
      label: Have you asked this question on our Discord server?
      description: Please first ask the question on our [Discord server](https://discord.gg/tZAfuWAbm2)!
      options:
        - label: I have already asked on Discord!
          required: true
